import { Cell } from '@/app/excel-studio/contexts/ExcelStudioContext';

export interface SampleDataset {
  id: string;
  title: string;
  category: string;
  description: string;
  rowsCount: number;
  colsCount: number;
  cells: Record<string, Cell>;
}

export const SAMPLE_DATASETS: SampleDataset[] = [
  {
    id: 'sales_performance',
    title: 'Sales Performance Analytics',
    category: 'Sales',
    description: 'Quarterly breakdown of Enterprise vs SMB revenue, costs, net profit, and YoY targets.',
    rowsCount: 20,
    colsCount: 10,
    cells: {
      '0,0': { address: { sheetId: 'sheet1', row: 0, col: 0 }, value: 'Segment', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF' } },
      '0,1': { address: { sheetId: 'sheet1', row: 0, col: 1 }, value: 'Q1 Revenue', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF', textAlign: 'right' } },
      '0,2': { address: { sheetId: 'sheet1', row: 0, col: 2 }, value: 'Q2 Revenue', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF', textAlign: 'right' } },
      '0,3': { address: { sheetId: 'sheet1', row: 0, col: 3 }, value: 'Q3 Revenue', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF', textAlign: 'right' } },
      '0,4': { address: { sheetId: 'sheet1', row: 0, col: 4 }, value: 'Q4 Revenue', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF', textAlign: 'right' } },
      '0,5': { address: { sheetId: 'sheet1', row: 0, col: 5 }, value: 'Annual Total', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF', textAlign: 'right' } },
      '0,6': { address: { sheetId: 'sheet1', row: 0, col: 6 }, value: 'Average/Qtr', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF', textAlign: 'right' } },
      '0,7': { address: { sheetId: 'sheet1', row: 0, col: 7 }, value: 'Target Status', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF', textAlign: 'center' } },

      '1,0': { address: { sheetId: 'sheet1', row: 1, col: 0 }, value: 'Enterprise Software' },
      '1,1': { address: { sheetId: 'sheet1', row: 1, col: 1 }, value: 125000, formatting: { numberFormat: 'currency' } },
      '1,2': { address: { sheetId: 'sheet1', row: 1, col: 2 }, value: 142000, formatting: { numberFormat: 'currency' } },
      '1,3': { address: { sheetId: 'sheet1', row: 1, col: 3 }, value: 138000, formatting: { numberFormat: 'currency' } },
      '1,4': { address: { sheetId: 'sheet1', row: 1, col: 4 }, value: 165000, formatting: { numberFormat: 'currency' } },
      '1,5': { address: { sheetId: 'sheet1', row: 1, col: 5 }, value: 570000, formula: '=SUM(B2:E2)', formatting: { bold: true, numberFormat: 'currency' } },
      '1,6': { address: { sheetId: 'sheet1', row: 1, col: 6 }, value: 142500, formula: '=AVERAGE(B2:E2)', formatting: { numberFormat: 'currency' } },
      '1,7': { address: { sheetId: 'sheet1', row: 1, col: 7 }, value: 'Target Met', formula: '=IF(F2>500000, "Target Met", "Below Target")', formatting: { bold: true, fontColor: '#00E5FF' } },

      '2,0': { address: { sheetId: 'sheet1', row: 2, col: 0 }, value: 'SMB Subscriptions' },
      '2,1': { address: { sheetId: 'sheet1', row: 2, col: 1 }, value: 45000, formatting: { numberFormat: 'currency' } },
      '2,2': { address: { sheetId: 'sheet1', row: 2, col: 2 }, value: 52000, formatting: { numberFormat: 'currency' } },
      '2,3': { address: { sheetId: 'sheet1', row: 2, col: 3 }, value: 49000, formatting: { numberFormat: 'currency' } },
      '2,4': { address: { sheetId: 'sheet1', row: 2, col: 4 }, value: 61000, formatting: { numberFormat: 'currency' } },
      '2,5': { address: { sheetId: 'sheet1', row: 2, col: 5 }, value: 207000, formula: '=SUM(B3:E3)', formatting: { bold: true, numberFormat: 'currency' } },
      '2,6': { address: { sheetId: 'sheet1', row: 2, col: 6 }, value: 51750, formula: '=AVERAGE(B3:E3)', formatting: { numberFormat: 'currency' } },
      '2,7': { address: { sheetId: 'sheet1', row: 2, col: 7 }, value: 'Target Met', formula: '=IF(F3>200000, "Target Met", "Below Target")', formatting: { bold: true, fontColor: '#00E5FF' } },

      '3,0': { address: { sheetId: 'sheet1', row: 3, col: 0 }, value: 'Professional Services' },
      '3,1': { address: { sheetId: 'sheet1', row: 3, col: 1 }, value: 28000, formatting: { numberFormat: 'currency' } },
      '3,2': { address: { sheetId: 'sheet1', row: 3, col: 2 }, value: 31000, formatting: { numberFormat: 'currency' } },
      '3,3': { address: { sheetId: 'sheet1', row: 3, col: 3 }, value: 29500, formatting: { numberFormat: 'currency' } },
      '3,4': { address: { sheetId: 'sheet1', row: 3, col: 4 }, value: 34000, formatting: { numberFormat: 'currency' } },
      '3,5': { address: { sheetId: 'sheet1', row: 3, col: 5 }, value: 122500, formula: '=SUM(B4:E4)', formatting: { bold: true, numberFormat: 'currency' } },
      '3,6': { address: { sheetId: 'sheet1', row: 3, col: 6 }, value: 30625, formula: '=AVERAGE(B4:E4)', formatting: { numberFormat: 'currency' } },
      '3,7': { address: { sheetId: 'sheet1', row: 3, col: 7 }, value: 'Target Met', formula: '=IF(F4>100000, "Target Met", "Below Target")', formatting: { bold: true, fontColor: '#00E5FF' } },

      '4,0': { address: { sheetId: 'sheet1', row: 4, col: 0 }, value: 'Grand Total', formatting: { bold: true } },
      '4,1': { address: { sheetId: 'sheet1', row: 4, col: 1 }, value: 198000, formula: '=SUM(B2:B4)', formatting: { bold: true, numberFormat: 'currency' } },
      '4,2': { address: { sheetId: 'sheet1', row: 4, col: 2 }, value: 225000, formula: '=SUM(C2:C4)', formatting: { bold: true, numberFormat: 'currency' } },
      '4,3': { address: { sheetId: 'sheet1', row: 4, col: 3 }, value: 216500, formula: '=SUM(D2:D4)', formatting: { bold: true, numberFormat: 'currency' } },
      '4,4': { address: { sheetId: 'sheet1', row: 4, col: 4 }, value: 260000, formula: '=SUM(E2:E4)', formatting: { bold: true, numberFormat: 'currency' } },
      '4,5': { address: { sheetId: 'sheet1', row: 4, col: 5 }, value: 899500, formula: '=SUM(F2:F4)', formatting: { bold: true, bgColor: '#00E5FF', fontColor: '#000000', numberFormat: 'currency' } },
    },
  },
  {
    id: 'finance_statements',
    title: 'Corporate Financial Statements',
    category: 'Finance',
    description: 'Income statement including Operating Revenue, COGS, Gross Profit, Expenses, EBIT, and Tax calculations.',
    rowsCount: 20,
    colsCount: 8,
    cells: {
      '0,0': { address: { sheetId: 'sheet1', row: 0, col: 0 }, value: 'Financial Metric', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF' } },
      '0,1': { address: { sheetId: 'sheet1', row: 0, col: 1 }, value: '2024 Actuals', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF', textAlign: 'right' } },
      '0,2': { address: { sheetId: 'sheet1', row: 0, col: 2 }, value: '2025 Actuals', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF', textAlign: 'right' } },
      '0,3': { address: { sheetId: 'sheet1', row: 0, col: 3 }, value: '2026 Forecast', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF', textAlign: 'right' } },

      '1,0': { address: { sheetId: 'sheet1', row: 1, col: 0 }, value: 'Gross Revenue' },
      '1,1': { address: { sheetId: 'sheet1', row: 1, col: 1 }, value: 1200000, formatting: { numberFormat: 'currency' } },
      '1,2': { address: { sheetId: 'sheet1', row: 1, col: 2 }, value: 1450000, formatting: { numberFormat: 'currency' } },
      '1,3': { address: { sheetId: 'sheet1', row: 1, col: 3 }, value: 1800000, formatting: { numberFormat: 'currency' } },

      '2,0': { address: { sheetId: 'sheet1', row: 2, col: 0 }, value: 'Cost of Goods Sold (COGS)' },
      '2,1': { address: { sheetId: 'sheet1', row: 2, col: 1 }, value: 480000, formatting: { numberFormat: 'currency' } },
      '2,2': { address: { sheetId: 'sheet1', row: 2, col: 2 }, value: 550000, formatting: { numberFormat: 'currency' } },
      '2,3': { address: { sheetId: 'sheet1', row: 2, col: 3 }, value: 680000, formatting: { numberFormat: 'currency' } },

      '3,0': { address: { sheetId: 'sheet1', row: 3, col: 0 }, value: 'Gross Profit', formatting: { bold: true } },
      '3,1': { address: { sheetId: 'sheet1', row: 3, col: 1 }, value: 720000, formula: '=B2-B3', formatting: { bold: true, numberFormat: 'currency' } },
      '3,2': { address: { sheetId: 'sheet1', row: 3, col: 2 }, value: 900000, formula: '=C2-C3', formatting: { bold: true, numberFormat: 'currency' } },
      '3,3': { address: { sheetId: 'sheet1', row: 3, col: 3 }, value: 1120000, formula: '=D2-D3', formatting: { bold: true, numberFormat: 'currency' } },
    },
  },
  {
    id: 'hr_payroll',
    title: 'HR & Employee Headcount',
    category: 'HR',
    description: 'Employee roster with departments, base salary, bonuses, performance score, and bonus calculation formulas.',
    rowsCount: 20,
    colsCount: 8,
    cells: {
      '0,0': { address: { sheetId: 'sheet1', row: 0, col: 0 }, value: 'Employee ID', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF' } },
      '0,1': { address: { sheetId: 'sheet1', row: 0, col: 1 }, value: 'Full Name', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF' } },
      '0,2': { address: { sheetId: 'sheet1', row: 0, col: 2 }, value: 'Department', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF' } },
      '0,3': { address: { sheetId: 'sheet1', row: 0, col: 3 }, value: 'Base Salary', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF', textAlign: 'right' } },
      '0,4': { address: { sheetId: 'sheet1', row: 0, col: 4 }, value: 'Rating (1-5)', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF', textAlign: 'right' } },
      '0,5': { address: { sheetId: 'sheet1', row: 0, col: 5 }, value: 'Bonus Amount', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF', textAlign: 'right' } },

      '1,0': { address: { sheetId: 'sheet1', row: 1, col: 0 }, value: 'EMP-101' },
      '1,1': { address: { sheetId: 'sheet1', row: 1, col: 1 }, value: 'Sarah Jenkins' },
      '1,2': { address: { sheetId: 'sheet1', row: 1, col: 2 }, value: 'Data Science' },
      '1,3': { address: { sheetId: 'sheet1', row: 1, col: 3 }, value: 125000, formatting: { numberFormat: 'currency' } },
      '1,4': { address: { sheetId: 'sheet1', row: 1, col: 4 }, value: 5 },
      '1,5': { address: { sheetId: 'sheet1', row: 1, col: 5 }, value: 18750, formula: '=IF(E2>=5, D2*0.15, D2*0.05)', formatting: { numberFormat: 'currency' } },

      '2,0': { address: { sheetId: 'sheet1', row: 2, col: 0 }, value: 'EMP-102' },
      '2,1': { address: { sheetId: 'sheet1', row: 2, col: 1 }, value: 'Marcus Vance' },
      '2,2': { address: { sheetId: 'sheet1', row: 2, col: 2 }, value: 'Engineering' },
      '2,3': { address: { sheetId: 'sheet1', row: 2, col: 3 }, value: 110000, formatting: { numberFormat: 'currency' } },
      '2,4': { address: { sheetId: 'sheet1', row: 2, col: 4 }, value: 4 },
      '2,5': { address: { sheetId: 'sheet1', row: 2, col: 5 }, value: 5500, formula: '=IF(E3>=5, D3*0.15, D3*0.05)', formatting: { numberFormat: 'currency' } },
    },
  },
  {
    id: 'retail_inventory',
    title: 'Retail Inventory Management',
    category: 'Retail',
    description: 'Product SKUs, unit cost, stock quantity, reorder threshold, and automated stock alerts.',
    rowsCount: 20,
    colsCount: 8,
    cells: {
      '0,0': { address: { sheetId: 'sheet1', row: 0, col: 0 }, value: 'SKU Code', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF' } },
      '0,1': { address: { sheetId: 'sheet1', row: 0, col: 1 }, value: 'Item Description', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF' } },
      '0,2': { address: { sheetId: 'sheet1', row: 0, col: 2 }, value: 'Unit Price', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF', textAlign: 'right' } },
      '0,3': { address: { sheetId: 'sheet1', row: 0, col: 3 }, value: 'Stock Qty', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF', textAlign: 'right' } },
      '0,4': { address: { sheetId: 'sheet1', row: 0, col: 4 }, value: 'Reorder Level', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF', textAlign: 'right' } },
      '0,5': { address: { sheetId: 'sheet1', row: 0, col: 5 }, value: 'Status Alert', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF', textAlign: 'center' } },

      '1,0': { address: { sheetId: 'sheet1', row: 1, col: 0 }, value: 'SKU-8801' },
      '1,1': { address: { sheetId: 'sheet1', row: 1, col: 1 }, value: 'Wireless Headphones Pro' },
      '1,2': { address: { sheetId: 'sheet1', row: 1, col: 2 }, value: 199, formatting: { numberFormat: 'currency' } },
      '1,3': { address: { sheetId: 'sheet1', row: 1, col: 3 }, value: 14 },
      '1,4': { address: { sheetId: 'sheet1', row: 1, col: 4 }, value: 25 },
      '1,5': { address: { sheetId: 'sheet1', row: 1, col: 5 }, value: 'REORDER NOW', formula: '=IF(D2<=E2, "REORDER NOW", "Stock OK")', formatting: { bold: true, fontColor: '#FF1744' } },
    },
  },
  {
    id: 'healthcare_metrics',
    title: 'Healthcare Patient Operations',
    category: 'Healthcare',
    description: 'Patient admissions, average stay length, procedure costs, and insurance reimbursement stats.',
    rowsCount: 20,
    colsCount: 8,
    cells: {
      '0,0': { address: { sheetId: 'sheet1', row: 0, col: 0 }, value: 'Ward Unit', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF' } },
      '0,1': { address: { sheetId: 'sheet1', row: 0, col: 1 }, value: 'Admissions', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF', textAlign: 'right' } },
      '0,2': { address: { sheetId: 'sheet1', row: 0, col: 2 }, value: 'Avg Length of Stay (Days)', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF', textAlign: 'right' } },
      '0,3': { address: { sheetId: 'sheet1', row: 0, col: 3 }, value: 'Daily Care Cost', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF', textAlign: 'right' } },
      '0,4': { address: { sheetId: 'sheet1', row: 0, col: 4 }, value: 'Total Unit Cost', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF', textAlign: 'right' } },

      '1,0': { address: { sheetId: 'sheet1', row: 1, col: 0 }, value: 'Cardiology' },
      '1,1': { address: { sheetId: 'sheet1', row: 1, col: 1 }, value: 145 },
      '1,2': { address: { sheetId: 'sheet1', row: 1, col: 2 }, value: 4.2 },
      '1,3': { address: { sheetId: 'sheet1', row: 1, col: 3 }, value: 1200, formatting: { numberFormat: 'currency' } },
      '1,4': { address: { sheetId: 'sheet1', row: 1, col: 4 }, value: 730800, formula: '=B2*C2*D2', formatting: { bold: true, numberFormat: 'currency' } },
    },
  },
  {
    id: 'banking_risk',
    title: 'Banking & Credit Risk Portfolio',
    category: 'Banking',
    description: 'Loan portfolios, credit scores, default probabilities, risk categories, and provision reserves.',
    rowsCount: 20,
    colsCount: 8,
    cells: {
      '0,0': { address: { sheetId: 'sheet1', row: 0, col: 0 }, value: 'Account No', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF' } },
      '0,1': { address: { sheetId: 'sheet1', row: 0, col: 1 }, value: 'Principal Loan', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF', textAlign: 'right' } },
      '0,2': { address: { sheetId: 'sheet1', row: 0, col: 2 }, value: 'Credit Score', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF', textAlign: 'right' } },
      '0,3': { address: { sheetId: 'sheet1', row: 0, col: 3 }, value: 'Risk Tier', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF', textAlign: 'center' } },

      '1,0': { address: { sheetId: 'sheet1', row: 1, col: 0 }, value: 'LN-90412' },
      '1,1': { address: { sheetId: 'sheet1', row: 1, col: 1 }, value: 350000, formatting: { numberFormat: 'currency' } },
      '1,2': { address: { sheetId: 'sheet1', row: 1, col: 2 }, value: 740 },
      '1,3': { address: { sheetId: 'sheet1', row: 1, col: 3 }, value: 'Low Risk', formula: '=IF(C2>700, "Low Risk", "High Risk")', formatting: { bold: true, fontColor: '#00E5FF' } },
    },
  },
  {
    id: 'supply_chain',
    title: 'Supply Chain & Logistics',
    category: 'Supply Chain',
    description: 'Shipment Tracking, origin, destination, transit days, lead time targets, and penalty calculations.',
    rowsCount: 20,
    colsCount: 8,
    cells: {
      '0,0': { address: { sheetId: 'sheet1', row: 0, col: 0 }, value: 'Shipment ID', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF' } },
      '0,1': { address: { sheetId: 'sheet1', row: 0, col: 1 }, value: 'Origin Port', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF' } },
      '0,2': { address: { sheetId: 'sheet1', row: 0, col: 2 }, value: 'Freight Cost', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF', textAlign: 'right' } },
      '0,3': { address: { sheetId: 'sheet1', row: 0, col: 3 }, value: 'Actual Days', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF', textAlign: 'right' } },
      '0,4': { address: { sheetId: 'sheet1', row: 0, col: 4 }, value: 'SLA Days', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF', textAlign: 'right' } },
      '0,5': { address: { sheetId: 'sheet1', row: 0, col: 5 }, value: 'SLA Status', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF', textAlign: 'center' } },

      '1,0': { address: { sheetId: 'sheet1', row: 1, col: 0 }, value: 'SHP-401' },
      '1,1': { address: { sheetId: 'sheet1', row: 1, col: 1 }, value: 'Shanghai' },
      '1,2': { address: { sheetId: 'sheet1', row: 1, col: 2 }, value: 4200, formatting: { numberFormat: 'currency' } },
      '1,3': { address: { sheetId: 'sheet1', row: 1, col: 3 }, value: 14 },
      '1,4': { address: { sheetId: 'sheet1', row: 1, col: 4 }, value: 12 },
      '1,5': { address: { sheetId: 'sheet1', row: 1, col: 5 }, value: 'Delayed', formula: '=IF(D2<=E2, "On Time", "Delayed")', formatting: { bold: true, fontColor: '#FF1744' } },
    },
  },
  {
    id: 'marketing_roi',
    title: 'Marketing Campaign ROI',
    category: 'Marketing',
    description: 'Multi-channel digital marketing spend, impressions, clicks, conversions, Customer Acquisition Cost (CAC), and ROI.',
    rowsCount: 20,
    colsCount: 8,
    cells: {
      '0,0': { address: { sheetId: 'sheet1', row: 0, col: 0 }, value: 'Channel', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF' } },
      '0,1': { address: { sheetId: 'sheet1', row: 0, col: 1 }, value: 'Ad Spend', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF', textAlign: 'right' } },
      '0,2': { address: { sheetId: 'sheet1', row: 0, col: 2 }, value: 'Conversions', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF', textAlign: 'right' } },
      '0,3': { address: { sheetId: 'sheet1', row: 0, col: 3 }, value: 'CAC ($)', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF', textAlign: 'right' } },

      '1,0': { address: { sheetId: 'sheet1', row: 1, col: 0 }, value: 'Google Search Ads' },
      '1,1': { address: { sheetId: 'sheet1', row: 1, col: 1 }, value: 15000, formatting: { numberFormat: 'currency' } },
      '1,2': { address: { sheetId: 'sheet1', row: 1, col: 2 }, value: 300 },
      '1,3': { address: { sheetId: 'sheet1', row: 1, col: 3 }, value: 50, formula: '=B2/C2', formatting: { numberFormat: 'currency' } },
    },
  },
  {
    id: 'manufacturing_yield',
    title: 'Manufacturing Yield & Defects',
    category: 'Manufacturing',
    description: 'Factory line output, total produced units, defect count, defect rate, and quality compliance status.',
    rowsCount: 20,
    colsCount: 8,
    cells: {
      '0,0': { address: { sheetId: 'sheet1', row: 0, col: 0 }, value: 'Factory Line', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF' } },
      '0,1': { address: { sheetId: 'sheet1', row: 0, col: 1 }, value: 'Produced Units', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF', textAlign: 'right' } },
      '0,2': { address: { sheetId: 'sheet1', row: 0, col: 2 }, value: 'Defects', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF', textAlign: 'right' } },
      '0,3': { address: { sheetId: 'sheet1', row: 0, col: 3 }, value: 'Defect Rate (%)', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF', textAlign: 'right' } },

      '1,0': { address: { sheetId: 'sheet1', row: 1, col: 0 }, value: 'Assembly Line Alpha' },
      '1,1': { address: { sheetId: 'sheet1', row: 1, col: 1 }, value: 50000 },
      '1,2': { address: { sheetId: 'sheet1', row: 1, col: 2 }, value: 450 },
      '1,3': { address: { sheetId: 'sheet1', row: 1, col: 3 }, value: 0.009, formula: '=C2/B2', formatting: { numberFormat: 'percent' } },
    },
  },
  {
    id: 'ecommerce_orders',
    title: 'E-Commerce Global Transactions',
    category: 'E-Commerce',
    description: 'Customer order logs, order value, shipping tier, discount applied, and final net payment.',
    rowsCount: 20,
    colsCount: 8,
    cells: {
      '0,0': { address: { sheetId: 'sheet1', row: 0, col: 0 }, value: 'Order ID', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF' } },
      '0,1': { address: { sheetId: 'sheet1', row: 0, col: 1 }, value: 'Subtotal', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF', textAlign: 'right' } },
      '0,2': { address: { sheetId: 'sheet1', row: 0, col: 2 }, value: 'Discount Rate', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF', textAlign: 'right' } },
      '0,3': { address: { sheetId: 'sheet1', row: 0, col: 3 }, value: 'Net Payable', formatting: { bold: true, bgColor: '#161B22', fontColor: '#00E5FF', textAlign: 'right' } },

      '1,0': { address: { sheetId: 'sheet1', row: 1, col: 0 }, value: 'ORD-7719' },
      '1,1': { address: { sheetId: 'sheet1', row: 1, col: 1 }, value: 250, formatting: { numberFormat: 'currency' } },
      '1,2': { address: { sheetId: 'sheet1', row: 1, col: 2 }, value: 0.1, formatting: { numberFormat: 'percent' } },
      '1,3': { address: { sheetId: 'sheet1', row: 1, col: 3 }, value: 225, formula: '=B2*(1-C2)', formatting: { bold: true, numberFormat: 'currency' } },
    },
  },
];
