import { Sheet, Cell } from '@/app/excel-studio/contexts/ExcelStudioContext';
import { colIndexToLetter, evaluateFormula } from './formulaEvaluator';

/**
 * Export active worksheet to CSV format string and download
 */
export function exportToCSV(sheet: Sheet, filename: string = 'export.csv') {
  const maxRow = findMaxRow(sheet.cells);
  const maxCol = findMaxCol(sheet.cells);

  const lines: string[] = [];
  for (let r = 0; r <= maxRow; r++) {
    const rowValues: string[] = [];
    for (let c = 0; c <= maxCol; c++) {
      const cell = sheet.cells[`${r},${c}`];
      let valStr = '';
      if (cell) {
        const evaluated = cell.formula ? evaluateFormula(cell.formula, sheet.cells) : cell.value;
        valStr = evaluated !== null && evaluated !== undefined ? String(evaluated) : '';
      }
      // Escape quotes and commas in CSV
      if (valStr.includes(',') || valStr.includes('"') || valStr.includes('\n')) {
        valStr = `"${valStr.replace(/"/g, '""')}"`;
      }
      rowValues.push(valStr);
    }
    lines.push(rowValues.join(','));
  }

  const csvContent = lines.join('\n');
  downloadFile(csvContent, filename, 'text/csv;charset=utf-8;');
}

/**
 * Export active worksheet to TSV format string and download
 */
export function exportToTSV(sheet: Sheet, filename: string = 'export.tsv') {
  const maxRow = findMaxRow(sheet.cells);
  const maxCol = findMaxCol(sheet.cells);

  const lines: string[] = [];
  for (let r = 0; r <= maxRow; r++) {
    const rowValues: string[] = [];
    for (let c = 0; c <= maxCol; c++) {
      const cell = sheet.cells[`${r},${c}`];
      let valStr = '';
      if (cell) {
        const evaluated = cell.formula ? evaluateFormula(cell.formula, sheet.cells) : cell.value;
        valStr = evaluated !== null && evaluated !== undefined ? String(evaluated) : '';
      }
      rowValues.push(valStr.replace(/\t/g, ' '));
    }
    lines.push(rowValues.join('\t'));
  }

  const tsvContent = lines.join('\n');
  downloadFile(tsvContent, filename, 'text/tab-separated-values;charset=utf-8;');
}

/**
 * Export active worksheet to printable PDF HTML report
 */
export function exportToPDF(sheet: Sheet, title: string = 'Excel Studio Pro Report') {
  const maxRow = findMaxRow(sheet.cells);
  const maxCol = findMaxCol(sheet.cells);

  let tableHtml = '<table style="border-collapse: collapse; width: 100%; font-family: sans-serif; font-size: 12px;">';
  
  // Header row
  tableHtml += '<tr style="background-color: #0D1117; color: #00E5FF;">';
  tableHtml += '<th style="border: 1px solid #333; padding: 6px; text-align: center;">#</th>';
  for (let c = 0; c <= maxCol; c++) {
    tableHtml += `<th style="border: 1px solid #333; padding: 6px; text-align: center;">${colIndexToLetter(c)}</th>`;
  }
  tableHtml += '</tr>';

  for (let r = 0; r <= maxRow; r++) {
    tableHtml += '<tr>';
    tableHtml += `<td style="border: 1px solid #ddd; padding: 6px; font-weight: bold; background-color: #f5f5f5; text-align: center;">${r + 1}</td>`;
    for (let c = 0; c <= maxCol; c++) {
      const cell = sheet.cells[`${r},${c}`];
      let valStr = '';
      let style = 'border: 1px solid #ddd; padding: 6px;';
      if (cell) {
        const evaluated = cell.formula ? evaluateFormula(cell.formula, sheet.cells) : cell.value;
        valStr = evaluated !== null && evaluated !== undefined ? String(evaluated) : '';
        if (cell.formatting?.bold) style += 'font-weight: bold;';
        if (cell.formatting?.italic) style += 'font-style: italic;';
        if (cell.formatting?.bgColor) style += `background-color: ${cell.formatting.bgColor};`;
        if (cell.formatting?.fontColor) style += `color: ${cell.formatting.fontColor};`;
        if (cell.formatting?.textAlign) style += `text-align: ${cell.formatting.textAlign};`;
      }
      tableHtml += `<td style="${style}">${valStr}</td>`;
    }
    tableHtml += '</tr>';
  }
  tableHtml += '</table>';

  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(`
      <html>
        <head>
          <title>${title}</title>
          <style>
            body { font-family: sans-serif; padding: 20px; color: #111; }
            h1 { color: #0088cc; font-size: 20px; border-bottom: 2px solid #0088cc; padding-bottom: 8px; }
            .meta { font-size: 10px; color: #666; margin-bottom: 20px; }
          </style>
        </head>
        <body>
          <h1>${title} - ${sheet.name}</h1>
          <div class="meta">Generated by AnalyticsRise Excel Studio Pro on ${new Date().toLocaleString()}</div>
          ${tableHtml}
          <script>
            window.onload = function() { window.print(); };
          </script>
        </body>
      </html>
    `);
    printWindow.document.close();
  }
}

// Helper: Download raw file content
function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function findMaxRow(cells: Record<string, Cell>): number {
  let max = 0;
  for (const key of Object.keys(cells)) {
    const r = parseInt(key.split(',')[0], 10);
    if (!isNaN(r) && r > max) max = r;
  }
  return Math.max(max, 10);
}

function findMaxCol(cells: Record<string, Cell>): number {
  let max = 0;
  for (const key of Object.keys(cells)) {
    const c = parseInt(key.split(',')[1], 10);
    if (!isNaN(c) && c > max) max = c;
  }
  return Math.max(max, 5);
}
