'use client';

import React, { useState, useEffect } from 'react';
import DashboardLayout from '@/app/components/layout/DashboardLayout';
import { motion, AnimatePresence } from 'framer-motion';

const EXAMS_LIST = [
  {
    id: 'exam-sql',
    title: 'SQL Relational Optimization Certification',
    category: 'SQL Databases',
    durationMinutes: 10,
    questionsCount: 5,
    difficulty: 'Intermediate',
    questions: [
      {
        text: 'Which SQL JOIN returns all rows from the left table and matched rows from the right table, filling with NULL if no match exists?',
        options: ['INNER JOIN', 'LEFT JOIN', 'RIGHT JOIN', 'FULL OUTER JOIN'],
        correct: 1
      },
      {
        text: 'What is the correct order of query execution phases in a relational database engine?',
        options: [
          'SELECT -> FROM -> WHERE -> GROUP BY',
          'FROM -> WHERE -> GROUP BY -> SELECT',
          'FROM -> SELECT -> WHERE -> GROUP BY',
          'WHERE -> FROM -> SELECT -> GROUP BY'
        ],
        correct: 1
      },
      {
        text: 'Which SQL keyword is used to filter aggregate groupings generated by a GROUP BY clause?',
        options: ['WHERE', 'HAVING', 'FILTER', 'OVER'],
        correct: 1
      },
      {
        text: 'Which database index type is best suited for range-based queries (e.g., column BETWEEN 10 AND 50)?',
        options: ['Hash Index', 'B-Tree Index', 'Bitmap Index', 'Spatial Index'],
        correct: 1
      },
      {
        text: 'What does a Common Table Expression (CTE) start with in SQL syntax?',
        options: ['WITH', 'SELECT AS', 'DECLARE', 'CREATE TEMP'],
        correct: 0
      }
    ]
  },
  {
    id: 'exam-excel',
    title: 'Excel Financial Modeling & Auditing Assessment',
    category: 'Spreadsheets',
    durationMinutes: 8,
    questionsCount: 3,
    difficulty: 'Advanced',
    questions: [
      {
        text: 'What is the correct syntax for a dynamic XLOOKUP to return matching values with an exact match mode?',
        options: [
          '=XLOOKUP(lookup_value, lookup_array, return_array)',
          '=XLOOKUP(lookup_value, lookup_array, return_array, 0, 1)',
          '=XLOOKUP(lookup_value, return_array, lookup_array)',
          '=XLOOKUP(lookup_value, lookup_array, return_array, -1)'
        ],
        correct: 0
      },
      {
        text: 'Which keyboard shortcut toggles formula auditing mode to show formulas inside cells instead of calculated values?',
        options: ['Ctrl + `', 'Ctrl + Shift + F', 'F9', 'Ctrl + Alt + V'],
        correct: 0
      },
      {
        text: 'What Excel feature is best suited to perform sensitivity analysis on two variables simultaneously?',
        options: ['Goal Seek', 'Data Table (2-input)', 'Scenario Manager', 'Solver'],
        correct: 1
      }
    ]
  }
];

export default function AssessmentsPage() {
  const [activeExam, setActiveExam] = useState<typeof EXAMS_LIST[0] | null>(null);
  const [questionIdx, setQuestionIdx] = useState(0);
  const [selectedOpt, setSelectedOpt] = useState<number | null>(null);
  const [answers, setAnswers] = useState<number[]>([]);
  const [timeLeft, setTimeLeft] = useState(0);
  const [score, setScore] = useState<number | null>(null);
  const [quizFinished, setQuizFinished] = useState(false);

  // Timer interval hook
  useEffect(() => {
    if (!activeExam || quizFinished) return;
    
    const timer = setInterval(() => {
      setTimeLeft((prev) => {
        if (prev <= 1) {
          clearInterval(timer);
          handleFinishQuiz(true); // timeout finish
          return 0;
        }
        return prev - 1;
      });
    }, 1000);

    return () => clearInterval(timer);
  }, [activeExam, quizFinished]);

  const handleStartExam = (exam: typeof EXAMS_LIST[0]) => {
    setActiveExam(exam);
    setQuestionIdx(0);
    setSelectedOpt(null);
    setAnswers([]);
    setTimeLeft(exam.durationMinutes * 60);
    setScore(null);
    setQuizFinished(false);
  };

  const handleNextQuestion = () => {
    if (selectedOpt === null) return;

    const newAnswers = [...answers, selectedOpt];
    setAnswers(newAnswers);
    setSelectedOpt(null);

    if (questionIdx + 1 < activeExam!.questions.length) {
      setQuestionIdx(questionIdx + 1);
    } else {
      handleFinishQuiz(false, newAnswers);
    }
  };

  const handleFinishQuiz = (timeout = false, finalAnswers = answers) => {
    setQuizFinished(true);

    let correctCount = 0;
    activeExam!.questions.forEach((q, idx) => {
      const userAns = finalAnswers[idx];
      if (userAns === q.correct) {
        correctCount++;
      }
    });

    const percent = Math.round((correctCount / activeExam!.questions.length) * 100);
    setScore(percent);
  };

  const handleExitExam = () => {
    setActiveExam(null);
    setScore(null);
    setQuizFinished(false);
  };

  return (
    <DashboardLayout>
      <div className="mb-8">
        <span className="text-xs text-slate-500 font-mono tracking-widest uppercase">Assessments Portal</span>
        <h1 className="text-2xl md:text-3xl font-black text-white tracking-wide font-display mt-1">
          TESTING & CERTIFICATION CENTER
        </h1>
        <p className="text-slate-400 text-sm mt-2">
          Verify your competence parameters. Achieve 80% or higher to unlock professional digital certificates.
        </p>
      </div>

      <AnimatePresence mode="wait">
        {!activeExam ? (
          <motion.div 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="grid md:grid-cols-2 gap-6"
          >
            {EXAMS_LIST.map((exam) => (
              <div key={exam.id} className="glass-panel p-6 flex flex-col justify-between h-56">
                <div>
                  <div className="flex justify-between items-start mb-3">
                    <span className="px-2 py-0.5 text-[9px] font-mono bg-white/5 rounded border border-white/5 text-[#00E5FF]">
                      {exam.category}
                    </span>
                    <span className="text-[10px] text-slate-500 font-mono">{exam.difficulty}</span>
                  </div>

                  <h3 className="text-lg font-bold text-white font-display uppercase tracking-wide leading-snug">
                    {exam.title}
                  </h3>
                  
                  <div className="flex items-center gap-4 mt-4 text-[11px] text-slate-400 font-mono">
                    <span>⏱ {exam.durationMinutes} Minutes</span>
                    <span>•</span>
                    <span>📋 {exam.questionsCount} Questions</span>
                  </div>
                </div>

                <div className="mt-6 pt-4 border-t border-white/5">
                  <button 
                    onClick={() => handleStartExam(exam)}
                    className="w-full py-2.5 cyber-button text-xs font-bold tracking-widest uppercase"
                  >
                    INITIALIZE EXAMINATION
                  </button>
                </div>
              </div>
            ))}
          </motion.div>
        ) : (
          <motion.div 
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            exit={{ opacity: 0 }}
            className="glass-panel p-8 bg-[#090D14] border border-[#00E5FF]/20 relative overflow-hidden"
          >
            <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-[#00E5FF] to-transparent" />
            
            {/* Header: Timer & active question counter */}
            {!quizFinished ? (
              <div className="flex justify-between items-center border-b border-white/5 pb-4 mb-6">
                <div>
                  <span className="text-[10px] text-slate-500 font-mono uppercase block">Active Session</span>
                  <h3 className="text-sm font-bold text-white font-display">{activeExam.title}</h3>
                </div>
                
                <div className="flex items-center gap-6 font-mono text-xs">
                  <div className="text-right">
                    <span className="text-slate-500 text-[10px] block uppercase">Progress</span>
                    <span className="text-white">Q {questionIdx + 1} of {activeExam.questions.length}</span>
                  </div>
                  <div className="text-right">
                    <span className="text-slate-500 text-[10px] block uppercase">Time Left</span>
                    <span className="text-[#00E5FF] font-bold text-sm">
                      {Math.floor(timeLeft / 60)}:{(timeLeft % 60).toString().padStart(2, '0')}
                    </span>
                  </div>
                </div>
              </div>
            ) : null}

            {/* Main Exam view */}
            {!quizFinished ? (
              <div className="space-y-6">
                {/* Question */}
                <h2 className="text-lg font-bold text-white leading-relaxed font-sans">
                  {activeExam.questions[questionIdx].text}
                </h2>

                {/* Options List */}
                <div className="space-y-3">
                  {activeExam.questions[questionIdx].options.map((opt, oIdx) => (
                    <div 
                      key={oIdx}
                      onClick={() => setSelectedOpt(oIdx)}
                      className={`p-4 rounded-lg border transition-all cursor-pointer text-xs font-mono flex items-center justify-between ${
                        selectedOpt === oIdx 
                          ? 'border-[#00E5FF] bg-[#00E5FF]/10 text-white font-bold' 
                          : 'border-white/5 bg-white/5 text-slate-400 hover:text-white hover:bg-white/10'
                      }`}
                    >
                      <span>{opt}</span>
                      {selectedOpt === oIdx && <span className="text-[10px] text-[#00E5FF]">SELECTED</span>}
                    </div>
                  ))}
                </div>

                <div className="mt-8 pt-6 border-t border-white/5 flex justify-end">
                  <button 
                    onClick={handleNextQuestion}
                    disabled={selectedOpt === null}
                    className="px-8 py-3 bg-[#00E5FF] hover:bg-[#00B8CC] disabled:opacity-50 text-black font-display font-bold text-xs tracking-widest uppercase rounded"
                  >
                    {questionIdx + 1 === activeExam.questions.length ? 'SUBMIT TEST' : 'NEXT QUESTION'}
                  </button>
                </div>
              </div>
            ) : (
              // Results Display
              <div className="text-center space-y-6 max-w-md mx-auto py-10">
                <div className="w-20 h-20 rounded-full border-2 mx-auto flex-center text-2xl font-mono font-bold border-glow bg-slate-900" style={{
                  borderColor: score! >= 80 ? '#00E676' : '#FF5252',
                  color: score! >= 80 ? '#00E676' : '#FF5252'
                }}>
                  {score}%
                </div>

                <div>
                  <h2 className="text-2xl font-black text-white font-display uppercase tracking-wider">
                    {score! >= 80 ? 'EXAM PASSED!' : 'EXAM FAILED'}
                  </h2>
                  <p className="text-xs text-slate-400 mt-2 leading-relaxed">
                    {score! >= 80 
                      ? 'Congratulations! You have verified your competence parameters. Certificate generated successfully.'
                      : 'You did not meet the passing threshold of 80%. Review curriculum modules and retake database assessments.'}
                  </p>
                </div>

                <div className="flex flex-col gap-3">
                  {score! >= 80 && (
                    <Link href="/certifications" className="w-full py-3 cyber-button text-xs font-bold tracking-widest">
                      CLAIM DIGITAL CERTIFICATE
                    </Link>
                  )}
                  <button 
                    onClick={handleExitExam}
                    className="w-full py-3 border border-white/5 bg-white/5 hover:bg-white/10 text-xs font-bold tracking-widest uppercase text-slate-400 rounded transition-colors"
                  >
                    RETURN TO CENTER
                  </button>
                </div>
              </div>
            )}
          </motion.div>
        )}
      </AnimatePresence>
    </DashboardLayout>
  );
}
