import { onCall, HttpsError, CallableRequest } from 'firebase-functions/v2/https';
import * as logger from 'firebase-functions/logger';
import { FieldValue, Timestamp } from 'firebase-admin/firestore';
import { db } from './index';

/**
 * Public Question Representation (Sanitized for client consumption)
 * Learners receive only text, options, and points. Never correct answers or indices.
 */
export interface PublicAssessmentQuestion {
  id: string;
  text: string;
  options: string[];
  points: number;
}

/**
 * Public Assessment Metadata
 */
export interface PublicAssessmentMetadata {
  id: string;
  title: string;
  category: string;
  courseId: string;
  durationMinutes: number;
  passingScore: number;
  totalQuestions: number;
  totalPoints: number;
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
  questions: PublicAssessmentQuestion[];
}

/**
 * Server-Only Private Answer Key Definition
 * Stored securely on the server / Firestore /assessmentAnswers/{id}.
 * NEVER exposed to client-side bundles or callable responses.
 */
export interface PrivateQuestionKey {
  correctIndex: number;
  points: number;
}

export interface PrivateAssessmentKey {
  assessmentId: string;
  passingScore: number;
  totalPoints: number;
  keys: Record<string, PrivateQuestionKey>;
}

/**
 * Authoritative Built-in Assessment Catalog
 * Serves as the immutable ground-truth curriculum for AnalyticsRise certifications.
 */
export const AUTHORITATIVE_ASSESSMENTS: Record<string, PublicAssessmentMetadata> = {
  'exam-sql': {
    id: 'exam-sql',
    title: 'SQL Relational Optimization Certification',
    category: 'SQL Databases',
    courseId: 'sql-01',
    durationMinutes: 10,
    passingScore: 80,
    totalQuestions: 5,
    totalPoints: 100,
    difficulty: 'Intermediate',
    questions: [
      {
        id: 'sql_q1',
        text: 'Which SQL JOIN returns all rows from the left table and matched rows from the right table, filling with NULL if no match exists?',
        options: ['INNER JOIN', 'LEFT JOIN', 'RIGHT JOIN', 'FULL OUTER JOIN'],
        points: 20,
      },
      {
        id: 'sql_q2',
        text: 'What is the correct order of query execution phases in a relational database engine?',
        options: [
          'SELECT -> FROM -> WHERE -> GROUP BY',
          'FROM -> WHERE -> GROUP BY -> SELECT',
          'FROM -> SELECT -> WHERE -> GROUP BY',
          'WHERE -> FROM -> SELECT -> GROUP BY',
        ],
        points: 20,
      },
      {
        id: 'sql_q3',
        text: 'Which SQL keyword is used to filter aggregate groupings generated by a GROUP BY clause?',
        options: ['WHERE', 'HAVING', 'FILTER', 'OVER'],
        points: 20,
      },
      {
        id: 'sql_q4',
        text: 'Which database index type is best suited for range-based queries (e.g., column BETWEEN 10 AND 50)?',
        options: ['Hash Index', 'B-Tree Index', 'Bitmap Index', 'Spatial Index'],
        points: 20,
      },
      {
        id: 'sql_q5',
        text: 'What does a Common Table Expression (CTE) start with in SQL syntax?',
        options: ['WITH', 'SELECT AS', 'DECLARE', 'CREATE TEMP'],
        points: 20,
      },
    ],
  },
  'exam-excel': {
    id: 'exam-excel',
    title: 'Excel Financial Modeling & Auditing Assessment',
    category: 'Spreadsheets',
    courseId: 'excel-01',
    durationMinutes: 8,
    passingScore: 80,
    totalQuestions: 3,
    totalPoints: 100,
    difficulty: 'Advanced',
    questions: [
      {
        id: 'excel_q1',
        text: 'What is the correct syntax for a dynamic XLOOKUP to return matching values with an exact match mode?',
        options: [
          '=XLOOKUP(lookup_value, lookup_array, return_array)',
          '=XLOOKUP(lookup_value, lookup_array, return_array, 0, 1)',
          '=XLOOKUP(lookup_value, return_array, lookup_array)',
          '=XLOOKUP(lookup_value, lookup_array, return_array, -1)',
        ],
        points: 35,
      },
      {
        id: 'excel_q2',
        text: 'Which keyboard shortcut toggles formula auditing mode to show formulas inside cells instead of calculated values?',
        options: ['Ctrl + `', 'Ctrl + Shift + F', 'F9', 'Ctrl + Alt + V'],
        points: 35,
      },
      {
        id: 'excel_q3',
        text: 'What Excel feature is best suited to perform sensitivity analysis on two variables simultaneously?',
        options: ['Goal Seek', 'Data Table (2-input)', 'Scenario Manager', 'Solver'],
        points: 30,
      },
    ],
  },
};

/**
 * Server-Authoritative Private Answer Keys
 * Kept exclusively in server memory and private Firestore /assessmentAnswers/{id}.
 */
export const AUTHORITATIVE_ANSWER_KEYS: Record<string, PrivateAssessmentKey> = {
  'exam-sql': {
    assessmentId: 'exam-sql',
    passingScore: 80,
    totalPoints: 100,
    keys: {
      sql_q1: { correctIndex: 1, points: 20 },
      sql_q2: { correctIndex: 1, points: 20 },
      sql_q3: { correctIndex: 1, points: 20 },
      sql_q4: { correctIndex: 1, points: 20 },
      sql_q5: { correctIndex: 0, points: 20 },
    },
  },
  'exam-excel': {
    assessmentId: 'exam-excel',
    passingScore: 80,
    totalPoints: 100,
    keys: {
      excel_q1: { correctIndex: 0, points: 35 },
      excel_q2: { correctIndex: 0, points: 35 },
      excel_q3: { correctIndex: 1, points: 30 },
    },
  },
};

/**
 * Retrieve public sanitized assessment metadata (Never returns answer keys)
 */
export async function getSanitizedAssessment(
  assessmentId: string,
  firestoreDb?: FirebaseFirestore.Firestore
): Promise<PublicAssessmentMetadata | null> {
  // Check authoritative built-in registry first
  if (AUTHORITATIVE_ASSESSMENTS[assessmentId]) {
    return AUTHORITATIVE_ASSESSMENTS[assessmentId];
  }

  // Fallback to Firestore /assessments/{assessmentId}
  const database = firestoreDb || db;
  const docRef = database.collection('assessments').doc(assessmentId);
  const snap = await docRef.get();
  if (snap.exists) {
    const data = snap.data();
    if (!data) return null;

    // Sanitize questions to ensure no answer keys or internal indices leak
    const rawQuestions = Array.isArray(data.questions) ? data.questions : [];
    const sanitizedQuestions: PublicAssessmentQuestion[] = rawQuestions.map((q: any, idx: number) => ({
      id: q.id || `q_${idx + 1}`,
      text: q.text || '',
      options: Array.isArray(q.options)
        ? q.options.map((opt: any) => (typeof opt === 'string' ? opt : opt.text || ''))
        : [],
      points: Number(q.points) || 20,
    }));

    const totalPoints = sanitizedQuestions.reduce((acc, q) => acc + q.points, 0);

    return {
      id: assessmentId,
      title: data.title || assessmentId,
      category: data.category || 'General Analytics',
      courseId: data.courseId || '',
      durationMinutes: Number(data.durationMinutes) || 10,
      passingScore: Number(data.passingScore) || 80,
      totalQuestions: sanitizedQuestions.length,
      totalPoints: totalPoints > 0 ? totalPoints : 100,
      difficulty: data.difficulty || 'Intermediate',
      questions: sanitizedQuestions,
    };
  }

  return null;
}

/**
 * Retrieve private answer key (Server-only Admin SDK access)
 */
export async function getAssessmentAnswerKey(
  assessmentId: string,
  firestoreDb?: FirebaseFirestore.Firestore
): Promise<PrivateAssessmentKey | null> {
  // Check authoritative built-in registry first
  if (AUTHORITATIVE_ANSWER_KEYS[assessmentId]) {
    return AUTHORITATIVE_ANSWER_KEYS[assessmentId];
  }

  // Fallback to private Firestore /assessmentAnswers/{assessmentId}
  const database = firestoreDb || db;
  const docRef = database.collection('assessmentAnswers').doc(assessmentId);
  const snap = await docRef.get();
  if (snap.exists) {
    const data = snap.data();
    if (!data || !data.keys) return null;

    return {
      assessmentId,
      passingScore: Number(data.passingScore) || 80,
      totalPoints: Number(data.totalPoints) || 100,
      keys: data.keys as Record<string, PrivateQuestionKey>,
    };
  }

  return null;
}

export interface StartAssessmentData {
  assessmentId: string;
}

export interface StartAssessmentResponse {
  attemptId: string;
  assessmentId: string;
  title: string;
  category: string;
  durationMinutes: number;
  passingScore: number;
  totalQuestions: number;
  totalPoints: number;
  startedAt: string;
  expiresAt: string;
  questions: PublicAssessmentQuestion[];
}

/**
 * Core business logic for starting an assessment attempt
 */
export async function processAssessmentStart(
  userId: string,
  data: StartAssessmentData,
  firestoreDb?: FirebaseFirestore.Firestore
): Promise<StartAssessmentResponse> {
  if (!userId || typeof userId !== 'string' || userId.trim() === '') {
    throw new HttpsError(
      'unauthenticated',
      'User must be authenticated with Firebase Auth to start an assessment.'
    );
  }

  if (!data || typeof data !== 'object' || !data.assessmentId || typeof data.assessmentId !== 'string') {
    throw new HttpsError(
      'invalid-argument',
      'Missing or invalid "assessmentId" parameter.'
    );
  }

  const assessmentId = data.assessmentId.trim();
  const assessment = await getSanitizedAssessment(assessmentId, firestoreDb);
  if (!assessment) {
    throw new HttpsError(
      'not-found',
      `Assessment with ID "${assessmentId}" does not exist or is currently unavailable.`
    );
  }

  if (assessment.questions.length === 0) {
    throw new HttpsError(
      'failed-precondition',
      `Assessment "${assessmentId}" contains no active questions.`
    );
  }

  const database = firestoreDb || db;
  const now = new Date();
  // Server-authoritative timer: duration in minutes + 60-second network buffer
  const durationSeconds = assessment.durationMinutes * 60;
  const expiresAtDate = new Date(now.getTime() + (durationSeconds + 60) * 1000);

  // Generate unique attempt identifier
  const attemptId = `att_${userId.substring(0, 8)}_${assessmentId}_${Date.now()}`;
  const attemptDocRef = database.collection('assessmentAttempts').doc(attemptId);

  await attemptDocRef.set({
    attemptId,
    userId,
    assessmentId,
    durationMinutes: assessment.durationMinutes,
    startedAt: Timestamp.fromDate(now),
    expiresAt: Timestamp.fromDate(expiresAtDate),
    status: 'in_progress',
    createdAt: FieldValue.serverTimestamp(),
    updatedAt: FieldValue.serverTimestamp(),
  });

  logger.info('Assessment attempt initialized:', {
    attemptId,
    userId,
    assessmentId,
    durationMinutes: assessment.durationMinutes,
    expiresAt: expiresAtDate.toISOString(),
  });

  return {
    attemptId,
    assessmentId: assessment.id,
    title: assessment.title,
    category: assessment.category,
    durationMinutes: assessment.durationMinutes,
    passingScore: assessment.passingScore,
    totalQuestions: assessment.totalQuestions,
    totalPoints: assessment.totalPoints,
    startedAt: now.toISOString(),
    expiresAt: expiresAtDate.toISOString(),
    questions: assessment.questions,
  };
}

export interface SubmitAssessmentData {
  attemptId: string;
  answers: Record<string, number>;
}

export interface SubmitAssessmentResponse {
  submissionId: string;
  attemptId: string;
  assessmentId: string;
  score: number;
  totalPoints: number;
  percentage: number;
  passingScore: number;
  passed: boolean;
  gradedAt: string;
  certificateEligible: boolean;
}

/**
 * Core business logic for grading and submitting an assessment attempt
 */
export async function processAssessmentSubmission(
  userId: string,
  data: SubmitAssessmentData,
  firestoreDb?: FirebaseFirestore.Firestore
): Promise<SubmitAssessmentResponse> {
  if (!userId || typeof userId !== 'string' || userId.trim() === '') {
    throw new HttpsError(
      'unauthenticated',
      'User must be authenticated with Firebase Auth to submit an assessment.'
    );
  }

  if (!data || typeof data !== 'object' || !data.attemptId || typeof data.attemptId !== 'string') {
    throw new HttpsError(
      'invalid-argument',
      'Missing or invalid "attemptId" in submission payload.'
    );
  }

  if (!data.answers || typeof data.answers !== 'object' || Array.isArray(data.answers)) {
    throw new HttpsError(
      'invalid-argument',
      'Answers must be a key-value mapping of question ID to selected option index.'
    );
  }

  const attemptId = data.attemptId.trim();
  const database = firestoreDb || db;
  const attemptDocRef = database.collection('assessmentAttempts').doc(attemptId);
  const attemptSnap = await attemptDocRef.get();

  if (!attemptSnap.exists) {
    throw new HttpsError(
      'not-found',
      `Assessment attempt "${attemptId}" was not found.`
    );
  }

  const attemptData = attemptSnap.data();
  if (attemptData?.userId !== userId) {
    throw new HttpsError(
      'permission-denied',
      'You are not authorized to submit this assessment attempt.'
    );
  }

  if (attemptData?.status === 'submitted') {
    throw new HttpsError(
      'failed-precondition',
      'This assessment attempt has already been submitted and scored.'
    );
  }

  // Authoritative server-side expiration validation
  const serverNow = new Date();
  const expiresAt: Date = attemptData?.expiresAt?.toDate
    ? attemptData.expiresAt.toDate()
    : new Date(attemptData?.expiresAt || 0);

  if (expiresAt.getTime() > 0 && serverNow.getTime() > expiresAt.getTime()) {
    logger.warn('Assessment submitted after expiration deadline:', {
      attemptId,
      userId,
      expiredAt: expiresAt.toISOString(),
      submittedAt: serverNow.toISOString(),
    });
    throw new HttpsError(
      'deadline-exceeded',
      'Assessment attempt deadline has expired. Submissions received after the time limit cannot be graded.'
    );
  }

  const assessmentId = attemptData?.assessmentId;
  const assessment = await getSanitizedAssessment(assessmentId, database);
  if (!assessment) {
    throw new HttpsError(
      'not-found',
      `Assessment definition "${assessmentId}" could not be loaded.`
    );
  }

  const answerKey = await getAssessmentAnswerKey(assessmentId, database);
  if (!answerKey || !answerKey.keys) {
    logger.error('Private answer key missing for assessment:', { assessmentId });
    throw new HttpsError(
      'internal',
      'Grading service configuration error. Private answer key is unavailable.'
    );
  }

  // Validate answer format and option bounds against public metadata
  const questionMap = new Map(assessment.questions.map((q) => [q.id, q]));
  for (const [qId, selectedIndex] of Object.entries(data.answers)) {
    if (!questionMap.has(qId)) {
      throw new HttpsError(
        'invalid-argument',
        `Unknown or unrecognized question ID in submission: "${qId}".`
      );
    }

    if (typeof selectedIndex !== 'number' || !Number.isInteger(selectedIndex) || selectedIndex < 0) {
      throw new HttpsError(
        'invalid-argument',
        `Invalid option index for question "${qId}". Index must be a non-negative integer.`
      );
    }

    const questionDef = questionMap.get(qId)!;
    if (selectedIndex >= questionDef.options.length) {
      throw new HttpsError(
        'invalid-argument',
        `Option index ${selectedIndex} is out of bounds for question "${qId}".`
      );
    }
  }

  // Server-Authoritative Grading
  let earnedPoints = 0;
  let totalPossiblePoints = 0;

  for (const question of assessment.questions) {
    const qKey = answerKey.keys[question.id];
    const qPoints = qKey?.points ?? question.points;
    totalPossiblePoints += qPoints;

    const userSelection = data.answers[question.id];
    if (userSelection !== undefined && qKey && userSelection === qKey.correctIndex) {
      earnedPoints += qPoints;
    }
  }

  const totalPoints = totalPossiblePoints > 0 ? totalPossiblePoints : 100;
  const percentage = Math.round((earnedPoints / totalPoints) * 100);
  const passed = percentage >= assessment.passingScore;

  // Deterministic submission document ID
  const submissionId = `sub_${attemptId}`;
  const submissionDocRef = database.collection('submissions').doc(submissionId);
  const gradedAtDate = new Date();

  // Atomically persist official submission and update attempt
  await database.runTransaction(async (transaction) => {
    // Write official submission
    transaction.set(submissionDocRef, {
      submissionId,
      userId,
      assessmentId,
      attemptId,
      score: earnedPoints,
      totalPoints,
      percentage,
      passingScore: assessment.passingScore,
      passed,
      submittedAnswers: data.answers,
      submittedAt: Timestamp.fromDate(serverNow),
      gradedAt: Timestamp.fromDate(gradedAtDate),
      createdAt: FieldValue.serverTimestamp(),
      updatedAt: FieldValue.serverTimestamp(),
    });

    // Mark attempt as submitted
    transaction.update(attemptDocRef, {
      status: 'submitted',
      submissionId,
      submittedAt: Timestamp.fromDate(serverNow),
      gradedAt: Timestamp.fromDate(gradedAtDate),
      score: earnedPoints,
      percentage,
      passed,
      updatedAt: FieldValue.serverTimestamp(),
    });

    // Update user telemetry in /users/{userId} if passed
    if (passed) {
      const userDocRef = database.collection('users').doc(userId);
      const userSnap = await transaction.get(userDocRef);
      if (userSnap.exists) {
        transaction.update(userDocRef, {
          'telemetry.assessmentsPassed': FieldValue.increment(1),
          'telemetry.xp': FieldValue.increment(250),
          'telemetry.lastActiveDate': new Date().toISOString().split('T')[0],
          updatedAt: FieldValue.serverTimestamp(),
        });
      }
    }
  });

  logger.info('Assessment graded and persisted successfully:', {
    submissionId,
    userId,
    assessmentId,
    score: earnedPoints,
    totalPoints,
    percentage,
    passed,
  });

  return {
    submissionId,
    attemptId,
    assessmentId,
    score: earnedPoints,
    totalPoints,
    percentage,
    passingScore: assessment.passingScore,
    passed,
    gradedAt: gradedAtDate.toISOString(),
    certificateEligible: passed,
  };
}

/**
 * Cloud Function v2 Callable: startAssessment
 *
 * Authenticated Firebase endpoint to start an authoritative timed exam session.
 */
export const startAssessment = onCall(
  {
    cors: true,
    maxInstances: 20,
  },
  async (request: CallableRequest<StartAssessmentData>): Promise<StartAssessmentResponse> => {
    if (!request.auth || !request.auth.uid) {
      throw new HttpsError(
        'unauthenticated',
        'User must be authenticated with Firebase Auth to start an assessment.'
      );
    }

    const userId = request.auth.uid;
    return processAssessmentStart(userId, request.data);
  }
);

/**
 * Cloud Function v2 Callable: submitAssessment
 *
 * Authenticated Firebase endpoint to grade and record official assessment submissions.
 */
export const submitAssessment = onCall(
  {
    cors: true,
    maxInstances: 20,
  },
  async (request: CallableRequest<SubmitAssessmentData>): Promise<SubmitAssessmentResponse> => {
    if (!request.auth || !request.auth.uid) {
      throw new HttpsError(
        'unauthenticated',
        'User must be authenticated with Firebase Auth to submit an assessment.'
      );
    }

    const userId = request.auth.uid;
    return processAssessmentSubmission(userId, request.data);
  }
);
