import { PublicChallenge } from '../types';

/**
 * Client-Safe Public Challenge Catalog
 * Contains ONLY public metadata, business scenarios, hints, and instructional contracts.
 * ZERO canonical solutions or protected validation logic are bundled here.
 */
export const PUBLIC_CHALLENGES: PublicChallenge[] = [
  {
    id: 'sql.select.001',
    productId: 'sql',
    trackId: 'sql-foundation',
    moduleId: 'sql-select',
    sequence: 1,
    title: 'Product Catalog Scout',
    difficulty: 'Beginner',
    skillTags: ['SELECT', 'PROJECTION'],
    prerequisites: [],
    datasetId: 'ecommerce',
    targetTable: 'products',
    objective: 'Retrieve the product name, category ID, and retail selling price for all available inventory items.',
    scenario: 'The inventory operations team needs a clean catalog overview of all product items and their standard retail prices.',
    instructions: [
      'Write a SQL query selecting the `name`, `category_id`, and `price` columns from the `products` table.',
      'Do not apply any filtering or sorting.',
    ],
    starterQuery: '-- Retrieve product name, category_id, and price\nSELECT \nFROM products;',
    hints: [
      {
        level: 1,
        title: 'Selecting Specific Columns',
        content: 'Use the SELECT keyword followed by the comma-separated column names you wish to retrieve.',
      },
      {
        level: 2,
        title: 'Specifying the Table Source',
        content: 'Ensure your query selects name, category_id, and price specifically FROM products.',
      },
      {
        level: 3,
        title: 'Query Blueprint',
        content: 'SELECT name, category_id, price FROM products;',
      },
    ],
    xpReward: 50,
    masteryThreshold: 100,
    unlockRules: {
      type: 'ALWAYS_UNLOCKED',
    },
  },
  {
    id: 'sql.select.002',
    productId: 'sql',
    trackId: 'sql-foundation',
    moduleId: 'sql-select',
    sequence: 2,
    title: 'Customer Directory Lookup',
    difficulty: 'Beginner',
    skillTags: ['SELECT', 'PROJECTION'],
    prerequisites: ['sql.select.001'],
    datasetId: 'ecommerce',
    targetTable: 'customers',
    objective: 'Query the customer registry to list all registered customers with their contact and location details.',
    scenario: 'Customer Support requires a directory extract containing customer identifiers, names, emails, and geographic locations.',
    instructions: [
      'Select `customer_id`, `first_name`, `last_name`, `email`, `city`, and `country` from the `customers` table.',
      'Ensure all six columns appear in the exact specified projection order.',
    ],
    starterQuery: '-- Query customer directory details\nSELECT \nFROM customers;',
    hints: [
      {
        level: 1,
        title: 'Multiple Column Projection',
        content: 'List each requested column separated by commas in your SELECT clause.',
      },
      {
        level: 2,
        title: 'Reviewing Column Names',
        content: 'Include customer_id, first_name, last_name, email, city, and country FROM customers.',
      },
      {
        level: 3,
        title: 'Query Blueprint',
        content: 'SELECT customer_id, first_name, last_name, email, city, country FROM customers;',
      },
    ],
    xpReward: 60,
    masteryThreshold: 100,
    unlockRules: {
      type: 'PREREQUISITE_CHALLENGES',
      prerequisiteChallengeIds: ['sql.select.001'],
    },
  },
  {
    id: 'sql.where.001',
    productId: 'sql',
    trackId: 'sql-foundation',
    moduleId: 'sql-where',
    sequence: 1,
    title: 'Enterprise Subscription Filter',
    difficulty: 'Beginner',
    skillTags: ['FILTERING', 'WHERE'],
    prerequisites: ['sql.select.002'],
    datasetId: 'saas',
    targetTable: 'subscriptions',
    objective: 'Identify all active Enterprise Scale subscriptions (plan_id = 5) generating recurring revenue for the business.',
    scenario: 'The Account Executive team needs an immediate list of all active enterprise client accounts (plan_id = 5) to schedule quarterly reviews.',
    instructions: [
      'Select `subscription_id`, `company_id`, `plan_id`, and `mrr` from the `subscriptions` table.',
      'Filter the rows where `plan_id = 5` and `status = \'active\'`.',
    ],
    starterQuery: '-- Filter for active Enterprise Scale subscriptions (plan_id = 5)\nSELECT subscription_id, company_id, plan_id, mrr\nFROM subscriptions\nWHERE ;',
    hints: [
      {
        level: 1,
        title: 'Applying Multiple Conditions',
        content: 'Use the WHERE clause and combine numeric and string comparison conditions using the AND keyword.',
      },
      {
        level: 2,
        title: 'Numeric and String Literals',
        content: "Specify the numeric plan ID without quotes and status with single quotes: plan_id = 5 AND status = 'active'.",
      },
      {
        level: 3,
        title: 'Query Blueprint',
        content: "SELECT subscription_id, company_id, plan_id, mrr FROM subscriptions WHERE plan_id = 5 AND status = 'active';",
      },
    ],
    xpReward: 75,
    masteryThreshold: 100,
    unlockRules: {
      type: 'PREREQUISITE_CHALLENGES',
      prerequisiteChallengeIds: ['sql.select.002'],
    },
  },
  {
    id: 'sql.where.002',
    productId: 'sql',
    trackId: 'sql-foundation',
    moduleId: 'sql-where',
    sequence: 2,
    title: 'VIP E-Commerce Shoppers',
    difficulty: 'Beginner',
    skillTags: ['FILTERING', 'WHERE'],
    prerequisites: ['sql.where.001'],
    datasetId: 'ecommerce',
    targetTable: 'customers',
    objective: 'Target high-value customers by filtering for shoppers in the Enterprise segment residing in the USA.',
    scenario: 'Marketing is rolling out a VIP loyalty campaign targeted exclusively at Enterprise segment customers in the USA.',
    instructions: [
      'Select `customer_id`, `first_name`, `last_name`, `email`, and `city` from the `customers` table.',
      'Filter for records where `segment` equals `\'Enterprise\'` and `country` equals `\'USA\'`.',
    ],
    starterQuery: '-- Filter for Enterprise segment customers in USA\nSELECT customer_id, first_name, last_name, email, city\nFROM customers\nWHERE ;',
    hints: [
      {
        level: 1,
        title: 'Segment and Country Filter',
        content: 'Combine the segment condition with country in your WHERE predicate.',
      },
      {
        level: 2,
        title: 'Case Sensitivity in String Literals',
        content: "Match the exact case: segment = 'Enterprise' AND country = 'USA'.",
      },
      {
        level: 3,
        title: 'Query Blueprint',
        content: "SELECT customer_id, first_name, last_name, email, city FROM customers WHERE segment = 'Enterprise' AND country = 'USA';",
      },
    ],
    xpReward: 80,
    masteryThreshold: 100,
    unlockRules: {
      type: 'PREREQUISITE_CHALLENGES',
      prerequisiteChallengeIds: ['sql.where.001'],
    },
  },
  {
    id: 'sql.orderby.001',
    productId: 'sql',
    trackId: 'sql-foundation',
    moduleId: 'sql-orderby-limit',
    sequence: 1,
    title: 'Top 5 Most Expensive Products',
    difficulty: 'Beginner',
    skillTags: ['SORTING', 'ORDER_BY', 'LIMIT'],
    prerequisites: ['sql.where.002'],
    datasetId: 'ecommerce',
    targetTable: 'products',
    objective: 'Extract the top 5 highest-priced products in the catalog to review premium pricing tiers.',
    scenario: 'The Merchandising Director wants to review the top 5 flagship products by retail selling price.',
    instructions: [
      'Select `product_id`, `name`, `category_id`, and `price` from the `products` table.',
      'Order the results by `price` in descending order (`DESC`).',
      'Limit the output to exactly 5 records.',
    ],
    starterQuery: '-- Find the 5 most expensive products\nSELECT product_id, name, category_id, price\nFROM products\nORDER BY \nLIMIT ;',
    hints: [
      {
        level: 1,
        title: 'Descending Sort Order',
        content: 'Use ORDER BY column_name DESC to rank numbers from highest to lowest.',
      },
      {
        level: 2,
        title: 'Restricting Result Count',
        content: 'Add LIMIT 5 at the end of the query following the ORDER BY clause.',
      },
      {
        level: 3,
        title: 'Query Blueprint',
        content: 'SELECT product_id, name, category_id, price FROM products ORDER BY price DESC LIMIT 5;',
      },
    ],
    xpReward: 90,
    masteryThreshold: 100,
    unlockRules: {
      type: 'PREREQUISITE_CHALLENGES',
      prerequisiteChallengeIds: ['sql.where.002'],
    },
  },
  {
    id: 'sql.orderby.002',
    productId: 'sql',
    trackId: 'sql-foundation',
    moduleId: 'sql-orderby-limit',
    sequence: 2,
    title: 'Executive Salary Rankings',
    difficulty: 'Beginner',
    skillTags: ['SORTING', 'ORDER_BY', 'LIMIT'],
    prerequisites: ['sql.orderby.001'],
    datasetId: 'hr',
    targetTable: 'employees',
    objective: 'Generate a list of top active employees sorted by department and earliest hire date to recognize senior tenure.',
    scenario: 'The HR department is planning a senior staff recognition program and requires active employee records sorted by department assignment and tenure date.',
    instructions: [
      'Select `employee_id`, `first_name`, `last_name`, `department_id`, and `hire_date` from the `employees` table.',
      'Filter for records where `employment_status` is equal to `\'Active\'`.',
      'Order the results first by `department_id` in ascending order (`ASC`), and then by `hire_date` in ascending order (`ASC`).',
      'Limit the output to 10 records.',
    ],
    starterQuery: '-- Retrieve active employees sorted by department and tenure\nSELECT employee_id, first_name, last_name, department_id, hire_date\nFROM employees\nWHERE employment_status = \'Active\'\nORDER BY \nLIMIT ;',
    hints: [
      {
        level: 1,
        title: 'Multi-Column Sorting',
        content: 'You can sort by multiple columns by separating them with commas: ORDER BY col1 ASC, col2 ASC.',
      },
      {
        level: 2,
        title: 'Filtering and Ordering Sequence',
        content: 'Ensure WHERE employment_status = \'Active\' comes before the ORDER BY clause.',
      },
      {
        level: 3,
        title: 'Query Blueprint',
        content: "SELECT employee_id, first_name, last_name, department_id, hire_date FROM employees WHERE employment_status = 'Active' ORDER BY department_id ASC, hire_date ASC LIMIT 10;",
      },
    ],
    xpReward: 100,
    masteryThreshold: 100,
    unlockRules: {
      type: 'PREREQUISITE_CHALLENGES',
      prerequisiteChallengeIds: ['sql.orderby.001'],
    },
  },
];
