import { ChallengeTrack, ChallengeModule } from './types';

export const SQL_TRACKS: ChallengeTrack[] = [
  {
    id: 'sql-foundation',
    productId: 'sql',
    title: 'SQL Foundation',
    description: 'Master the fundamental building blocks of querying relational databases.',
    sequence: 1,
    difficulty: 'Beginner',
    icon: 'Database',
  },
  {
    id: 'data-analysis-core',
    productId: 'sql',
    title: 'Data Analysis Core',
    description: 'Learn aggregation, grouping, and metrics calculation across datasets.',
    sequence: 2,
    difficulty: 'Intermediate',
    icon: 'BarChart3',
  },
  {
    id: 'relational-sql',
    productId: 'sql',
    title: 'Relational SQL',
    description: 'Connect multi-table databases using INNER, LEFT, and multi-way relational joins.',
    sequence: 3,
    difficulty: 'Intermediate',
    icon: 'Network',
  },
  {
    id: 'analytical-thinking',
    productId: 'sql',
    title: 'Analytical Thinking',
    description: 'Solve complex business problems using Subqueries, CTEs, and CASE statements.',
    sequence: 4,
    difficulty: 'Advanced',
    icon: 'BrainCircuit',
  },
  {
    id: 'advanced-analytics',
    productId: 'sql',
    title: 'Advanced Analytics',
    description: 'Compute rankings, running totals, and moving averages with Window functions.',
    sequence: 5,
    difficulty: 'Advanced',
    icon: 'TrendingUp',
  },
  {
    id: 'real-world-sql',
    productId: 'sql',
    title: 'Real-World SQL & Investigation',
    description: 'Investigate enterprise operational anomalies, churn patterns, and clean real-world data.',
    sequence: 6,
    difficulty: 'Advanced',
    icon: 'Briefcase',
  },
];

export const SQL_MODULES: ChallengeModule[] = [
  // Track 1: SQL Foundation
  {
    id: 'sql-select',
    trackId: 'sql-foundation',
    productId: 'sql',
    title: 'SELECT & Projections',
    description: 'Retrieve and project specific columns from single relational tables.',
    sequence: 1,
    difficulty: 'Beginner',
    skillsTaught: ['SELECT', 'PROJECTION'],
  },
  {
    id: 'sql-where',
    trackId: 'sql-foundation',
    productId: 'sql',
    title: 'WHERE Filtering & Logic',
    description: 'Filter rows using comparison operators, logical conditions, and pattern matching.',
    sequence: 2,
    difficulty: 'Beginner',
    prerequisites: ['sql-select'],
    skillsTaught: ['FILTERING', 'WHERE'],
  },
  {
    id: 'sql-orderby-limit',
    trackId: 'sql-foundation',
    productId: 'sql',
    title: 'ORDER BY & LIMIT Sorting',
    description: 'Sort query results deterministically and limit result sets for top-N ranking.',
    sequence: 3,
    difficulty: 'Beginner',
    prerequisites: ['sql-where'],
    skillsTaught: ['SORTING', 'ORDER_BY', 'LIMIT'],
  },

  // Track 2: Data Analysis Core
  {
    id: 'sql-aggregations',
    trackId: 'data-analysis-core',
    productId: 'sql',
    title: 'Aggregations & Math',
    description: 'Calculate metrics using COUNT, SUM, AVG, MIN, and MAX aggregate functions.',
    sequence: 1,
    difficulty: 'Intermediate',
    prerequisites: ['sql-orderby-limit'],
    skillsTaught: ['AGGREGATION'],
  },
  {
    id: 'sql-groupby-having',
    trackId: 'data-analysis-core',
    productId: 'sql',
    title: 'GROUP BY & HAVING Clauses',
    description: 'Segment data across dimensions and filter grouped metrics with HAVING.',
    sequence: 2,
    difficulty: 'Intermediate',
    prerequisites: ['sql-aggregations'],
    skillsTaught: ['GROUP_BY', 'HAVING'],
  },

  // Track 3: Relational SQL
  {
    id: 'sql-joins-inner',
    trackId: 'relational-sql',
    productId: 'sql',
    title: 'INNER JOIN Operations',
    description: 'Combine related tables matching foreign and primary keys across schemas.',
    sequence: 1,
    difficulty: 'Intermediate',
    prerequisites: ['sql-groupby-having'],
    skillsTaught: ['JOIN', 'INNER_JOIN'],
  },
  {
    id: 'sql-joins-outer',
    trackId: 'relational-sql',
    productId: 'sql',
    title: 'LEFT & Multi-table JOINs',
    description: 'Retain unmatched records with LEFT JOIN and stitch together three or more tables.',
    sequence: 2,
    difficulty: 'Intermediate',
    prerequisites: ['sql-joins-inner'],
    skillsTaught: ['JOIN', 'LEFT_JOIN'],
  },

  // Track 4: Analytical Thinking
  {
    id: 'sql-subqueries-ctes',
    trackId: 'analytical-thinking',
    productId: 'sql',
    title: 'Subqueries & CTEs',
    description: 'Structure modular analytical pipelines using Common Table Expressions and nested queries.',
    sequence: 1,
    difficulty: 'Advanced',
    prerequisites: ['sql-joins-outer'],
    skillsTaught: ['SUBQUERY', 'CTE'],
  },
  {
    id: 'sql-case-when',
    trackId: 'analytical-thinking',
    productId: 'sql',
    title: 'CASE WHEN Conditional Logic',
    description: 'Implement dynamic branching, tier labeling, and categorical pivoting.',
    sequence: 2,
    difficulty: 'Advanced',
    prerequisites: ['sql-subqueries-ctes'],
    skillsTaught: ['CASE_WHEN'],
  },

  // Track 5: Advanced Analytics
  {
    id: 'sql-window-functions',
    trackId: 'advanced-analytics',
    productId: 'sql',
    title: 'Window Functions & Ranking',
    description: 'Perform advanced analytical partitioning with ROW_NUMBER, RANK, and running sums.',
    sequence: 1,
    difficulty: 'Advanced',
    prerequisites: ['sql-case-when'],
    skillsTaught: ['WINDOW_FUNCTIONS', 'RANKING'],
  },

  // Track 6: Real-World SQL
  {
    id: 'sql-business-investigation',
    trackId: 'real-world-sql',
    productId: 'sql',
    title: 'Business Investigation & Data Cleaning',
    description: 'Diagnose data quality issues, anomalies, and deliver executive-grade insights.',
    sequence: 1,
    difficulty: 'Advanced',
    prerequisites: ['sql-window-functions'],
    skillsTaught: ['DATA_CLEANING', 'ANALYTICAL_INVESTIGATION'],
  },
];
